spring:
  application:
    name: campus-service
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgres:5432/campus_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
  servlet:
    context-path: /campus-service/api/v1
