server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      loadbalancer:
        cache:
          enabled: true
          caffeine:
            spec: initialCapacity=10,maximumSize=500,expireAfterWrite=5m
        health-check:
          path:
            default: /actuator/health
