server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      loadbalancer:
        cache:
          enabled: true
          caffeine:
            spec: initialCapacity=10,maximumSize=500,expireAfterWrite=5m
        health-check:
          path:
            default: /actuator/health

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${PEERS_URLS}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    enable:
      jvm: true
      process: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.cloud.gateway: ${LOG_LEVEL:INFO}
    org.springframework.http.server.reactive: INFO
    org.springframework.web: INFO
    com.olo.campusservice: WARN
