spring:
  application:
    name: campus-service
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgres:5432/campus_db
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:KAFKA:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all 
      retries: 5
      properties:
        spring.json.add.type.headers: false 
        
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 8081
  servlet:
    context-path: /campus-service/api/v1

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.150:8761/eureka/,http://192.168.1.150:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true
      process: true

logging:
  level:
    org.springframework.web: INFO
    com.olo.campusservice: DEBUG
