spring:
  datasource:
    username: postgres
    password: Oswaldolo089
    url: jdbc:postgresql://postgres:5432/student_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8080
  servlet:
    context-path: /student-service/api/v1
