server:
  port: 9000
  servlet:
    context-path: /auth-service/api

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: auth-service-dev

spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: auth-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_service
    username: ${DB_POSTGRES_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: Oswaldolo663@gmail.com
    password: yoot fmiw dmmm vqwy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
base-url:
  signup: http://127.0.0.1:5500/index.html?token=

jwt:
  secret:
    key: "${SECRET_KEY}"
  access-token:
    expiration:
      minutes: 24
  refresh-token:
    expiration:
      days: 15

cors:
  allowed-origins:
    - https://www.frontend-a.com
    - https://www.frontend-b.com
    - http://localhost:3000
    - http://127.0.0.1:5500

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-produces-media-type: application/json
  paths-to-match:
    - /validate/**

logging:
  level:
    root: INFO
    org.hibernate:
      orm:
        jdbc:
          bind: TRACE
    org.springframework:
      orm:
        jpa: DEBUG
      data: DEBUG
      web: DEBUG
      kafka: INFO
    org.apache:
      kafka: INFO
    com.zaxxer.hikari: DEBUG
