spring:
  application:
    name: auth-service
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgres:5432/auth_db
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:KAFKA:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all 
      retries: 5
      
      properties:
        spring.json.add.type.headers: false 
    consumer:
      group-id: auth-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
        
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 9000
  servlet:
    context-path: /auth-service/api/v1

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.150:8761/eureka,http://192.168.1.150:8762/eureka
jwt:
  secret:
    key: ${AUTH_SECRET_KEY}
  access-token:
    expiration:
      minutes: 24
  refresh-token:
    expiration: 
      days: 15
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true
      process: true

logging:
  level:
    org.springframework.web: INFO
